System.out.print()
System.out.print("忍者")
System.out.print("忍者")
System.out.print("忍者")
System.out.print("忍者")
System.out.print("忍者")
System.out.print("忍者")
System.out.print("忍者")
System.out.print("忍者")
System.out.print("你是个好人")
System.out.print("忍者")
System.out.print("忍者")
System.out.print("忍者")
System.out.print("忍者")
System.out.print("忍者")
System.out.print("忍者")

